const itemMetadata = {
/*General*/
"Shell Credits": { group: "aa", category: "general", rank: 1, image: "ww_icons/general/shell_credit.webp"},
// "Basic Resonance Potion": { group: "ab",  category: "general", rank: 1, image: "ww_icons/general/basic_resonance_potion.webp"},
// "Medium Resonance Potion": { group: "ab",  category: "general", rank: 2, image: "ww_icons/general/medium_resonance_potion.webp"},
// "Advanced Resonance Potion": { group: "ab",  category: "general", rank: 3, image: "ww_icons/general/advanced_resonance_potion.webp"},
// "Premium Resonance Potion": { group: "ab",  category: "general", rank: 4, image: "ww_icons/general/premium_resonance_potion.webp"},
"exp1": { group: "ab", category: "general", rank: 1, image: "ww_icons/general/basic_resonance_potion.webp"},
"exp2": { group: "ab", category: "general", rank: 2, image: "ww_icons/general/medium_resonance_potion.webp"},
"exp3": { group: "ab", category: "general", rank: 3, image: "ww_icons/general/advanced_resonance_potion.webp"},
"exp4": { group: "ab", category: "general", rank: 4, image: "ww_icons/general/premium_resonance_potion.webp"},
"expW1": { group: "ac", category: "general", rank: 1, image: "ww_icons/general/Basic_Energy_Core.png"},
"expW2": { group: "ac", category: "general", rank: 2, image: "ww_icons/general/Medium_Energy_Core.png"},
"expW3": { group: "ac", category: "general", rank: 3, image: "ww_icons/general/Advanced_Energy_Core.png"},
"expW4": { group: "ac", category: "general", rank: 4, image: "ww_icons/general/Premium_Energy_Core.png"},

/*Enemy Drops*/
"TBC1": { group: "b", category: "enemy", rank: 0, image: "ww_icons/general/tbc1.webp"},
"LF Whisperin Core": { group: "ba", category: "enemy", rank: 1, image: "ww_icons/skill_mat/lf_whisperin_core.webp"},
"MF Whisperin Core": { group: "ba", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mf_whisperin_core.webp"},
"HF Whisperin Core": { group: "ba", category: "enemy", rank: 3, image: "ww_icons/skill_mat/hf_whisperin_core.webp"},
"FF Whisperin Core": { group: "ba", category: "enemy", rank: 4, image: "ww_icons/skill_mat/ff_whisperin_core.webp"},
"LF Howler Core": { group: "bb", category: "enemy", rank: 1, image: "ww_icons/skill_mat/lf_howler_core.webp"},
"MF Howler Core": { group: "bb", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mf_howler_core.webp"},
"HF Howler Core": { group: "bb", category: "enemy", rank: 3, image: "ww_icons/skill_mat/hf_howler_core.webp"},
"FF Howler Core": { group: "bb", category: "enemy", rank: 4, image: "ww_icons/skill_mat/ff_howler_core.webp"},
"Crude Ring": { group: "bc", category: "enemy", rank: 1, image: "ww_icons/skill_mat/crude_ring.webp"},
"Basic Ring": { group: "bc", category: "enemy", rank: 2, image: "ww_icons/skill_mat/basic_ring.webp"},
"Improved Ring": { group: "bc", category: "enemy", rank: 3, image: "ww_icons/skill_mat/improved_ring.webp"},
"Tailored Ring": { group: "bc", category: "enemy", rank: 4, image: "ww_icons/skill_mat/tailored_ring.webp"},
"LF Polygon Core": { group: "bd", category: "enemy", rank: 1, image: "ww_icons/skill_mat/lf_polygon_core.webp"},
"MF Polygon Core": { group: "bd", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mf_polygon_core.webp"},
"HF Polygon Core": { group: "bd", category: "enemy", rank: 3, image: "ww_icons/skill_mat/hf_polygon_core.webp"},
"FF Polygon Core": { group: "bd", category: "enemy", rank: 4, image: "ww_icons/skill_mat/ff_polygon_core.webp"},
"LF Tidal Residuum": { group: "be", category: "enemy", rank: 1, image: "ww_icons/skill_mat/lf_tidal_residuum.webp"},
"MF Tidal Residuum": { group: "be", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mf_tidal_residuum.webp"},
"HF Tidal Residuum": { group: "be", category: "enemy", rank: 3, image: "ww_icons/skill_mat/hf_tidal_residuum.webp"},
"FF Tidal Residuum": { group: "be", category: "enemy", rank: 4, image: "ww_icons/skill_mat/ff_tidal_residuum.webp"},
"Mask of Constraint": { group: "bf", category: "enemy", rank: 1, image: "ww_icons/skill_mat/mask_of_constraint.webp"},
"Mask of Erosion": { group: "bf", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mask_of_erosion.webp"},
"Mask of Distortion": { group: "bf", category: "enemy", rank: 3, image: "ww_icons/skill_mat/mask_of_distortion.webp"},
"Mask of Insanity": { group: "bf", category: "enemy", rank: 4, image: "ww_icons/skill_mat/mask_of_insanity.webp"},
"LF Exoswarm Core": { group: "bg", category: "enemy", rank: 1, image: "ww_icons/skill_mat/tbc1.webp"},
"MF Exoswarm Core": { group: "bg", category: "enemy", rank: 2, image: "ww_icons/skill_mat/tbc1.webp"},
"HF Exoswarm Core": { group: "bg", category: "enemy", rank: 3, image: "ww_icons/skill_mat/tbc1.webp"},
"FF Exoswarm Core": { group: "bg", category: "enemy", rank: 4, image: "ww_icons/skill_mat/tbc1.webp"},
"LF Mech Core": { group: "bh", category: "enemy", rank: 1, image: "ww_icons/skill_mat/tbc1.webp"},
"MF Mech Core": { group: "bh", category: "enemy", rank: 2, image: "ww_icons/skill_mat/tbc1.webp"},
"HF Mech Core": { group: "bh", category: "enemy", rank: 3, image: "ww_icons/skill_mat/tbc1.webp"},
"FF Mech Core": { group: "bh", category: "enemy", rank: 4, image: "ww_icons/skill_mat/tbc1.webp"},

/*Weekly Material*/
"Monument Bell": { group: "ca", category: "weekly", rank: 3, image: "ww_icons/skill_mat/monumnet_bell.webp"},
"Unending Destruction": { group: "cb", category: "weekly", rank: 3, image: "ww_icons/skill_mat/unending_destruction.webp"},
"Dreamless Feather": { group: "cc", category: "weekly", rank: 3, image: "ww_icons/skill_mat/dreamless_feather.webp"},
"Sentinel's Dagger": { group: "cd", category: "weekly", rank: 3, image: "ww_icons/skill_mat/sentinels_dagger.webp"},
"The Netherworld's Stare": { group: "ce", category: "weekly", rank: 3, image: "ww_icons/skill_mat/the_netherworlds_stare.webp"},
"When Irises Bloom": { group: "cf", category: "weekly", rank: 3, image: "ww_icons/skill_mat/when_irises_bloom.webp"},
"Curse of the Abyss": { group: "cg", category: "weekly", rank: 3, image: "ww_icons/skill_mat/curse_of_the_abyss.webp"},

/*Boss Material*/
"TBC2": { group: "d", category: "boss", rank: 3, image: "ww_icons/general/tbc2.webp"},
"Strife Tacet Core": { group: "da", category: "boss", rank: 3, image: "ww_icons/res_mat/strife_tacet_core.webp"},
"Thundering Tacet Core": { group: "db", category: "boss", rank: 3, image: "ww_icons/res_mat/thundering_tacet_core.webp"},
"Elegy Tacet Core": { group: "dc", category: "boss", rank: 3, image: "ww_icons/res_mat/elegy_tacet_core.webp"},
"Rage Tacet Core": { group: "dd", category: "boss", rank: 3, image: "ww_icons/res_mat/rage_tacet_core.webp"},
"Roaring Rock Fist": { group: "de", category: "boss", rank: 3, image: "ww_icons/res_mat/roaring_rock_fist.webp"},
"Gold-Dissolving Feather": { group: "df", category: "boss", rank: 3, image: "ww_icons/res_mat/gold_dissolving_feather.webp"},
"Sound-Keeping Tacet Core": { group: "dg", category: "boss", rank: 3, image: "ww_icons/res_mat/sound_keeping_tacet_core.webp"},
"Group Abomination Tacet Core": { group: "dh", category: "boss", rank: 3, image: "ww_icons/res_mat/group_abomination_tacet_core.webp"},
"Hidden Thunder Tacet Core": { group: "di", category: "boss", rank: 3, image: "ww_icons/res_mat/hidden_thunder_tacet_core.webp"},
"Topological Confinement": { group: "dj", category: "boss", rank: 3, image: "ww_icons/res_mat/topological_confinement.webp"},
"Blazing Bone": { group: "dk", category: "boss", rank: 3, image: "ww_icons/res_mat/blazing_bone.webp"},
"Cleansing Conch": { group: "dl", category: "boss", rank: 3, image: "ww_icons/res_mat/cleansing_conch.webp"},
"Platinum Core": { group: "dm", category: "boss", rank: 3, image: "ww_icons/res_mat/platinum_core.webp"},
"Unfading Glory": { group: "dn", category: "boss", rank: 3, image: "ww_icons/res_mat/unfading_glory.webp"},
"Truth in Lies": { group: "do", category: "boss", rank: 3, image: "ww_icons/res_mat/truth_in_lies.webp"},
"Blighted Crown of Puppet King": { group: "dp", category: "boss", rank: 3, image: "ww_icons/res_mat/blighted_crown_of_puppet_king.webp"},
"Abyssal Husk": { group: "dq", category: "boss", rank: 3, image: "ww_icons/res_mat/abyssal_husk.webp"},

/*Domain Drops*/
"TBC3": { group: "e", category: "domain", rank: 0, image: "ww_icons/general/tbc3.webp"},
"Inert Metallic Drip": { group: "ea", category: "domain", rank: 1, image: "ww_icons/skill_mat/inert_metallic_drip.webp"},
"Reactive Metallic Drip": { group: "ea", category: "domain", rank: 2, image: "ww_icons/skill_mat/reactive_metallic_drip.webp"},
"Polarized Metallic Drip": { group: "ea", category: "domain", rank: 3, image: "ww_icons/skill_mat/polarized_metallic_drip.webp"},
"Heterized Metallic Drip": { group: "ea", category: "domain", rank: 4, image: "ww_icons/skill_mat/heterized_metallic_drip.webp"},
"Impure Phlogiston": { group: "eb", category: "domain", rank: 1, image: "ww_icons/skill_mat/impure_phlogiston.webp"},
"Extracted Phlogiston": { group: "eb", category: "domain", rank: 2, image: "ww_icons/skill_mat/extracted_phlogiston.webp"},
"Refined Phlogiston": { group: "eb", category: "domain", rank: 3, image: "ww_icons/skill_mat/refined_phlogiston.webp"},
"Flawless Phlogiston": { group: "eb", category: "domain", rank: 4, image: "ww_icons/skill_mat/flawless_phlogiston.webp"},
"Lento Helix": { group: "ec", category: "domain", rank: 1, image: "ww_icons/skill_mat/lento_helix.webp"},
"Adagio Helix": { group: "ec", category: "domain", rank: 2, image: "ww_icons/skill_mat/adagio_helix.webp"},
"Andante Helix": { group: "ec", category: "domain", rank: 3, image: "ww_icons/skill_mat/andante_helix.webp"},
"Presto Helix": { group: "ec", category: "domain", rank: 4, image: "ww_icons/skill_mat/presto_helix.webp"},
"Waveworn Residue 210": { group: "ed", category: "domain", rank: 1, image: "ww_icons/skill_mat/waveworn_residue_210.webp"},
"Waveworn Residue 226": { group: "ed", category: "domain", rank: 2, image: "ww_icons/skill_mat/waveworn_residue_226.webp"},
"Waveworn Residue 235": { group: "ed", category: "domain", rank: 3, image: "ww_icons/skill_mat/waveworn_residue_235.webp"},
"Waveworn Residue 239": { group: "ed", category: "domain", rank: 4, image: "ww_icons/skill_mat/waveworn_residue_239.webp"},
"Cadence Seed": { group: "ee", category: "domain", rank: 1, image: "ww_icons/skill_mat/cadence_seed.webp"},
"Cadence Bud": { group: "ee", category: "domain", rank: 2, image: "ww_icons/skill_mat/cadence_bud.webp"},
"Cadence Leaf": { group: "ee", category: "domain", rank: 3, image: "ww_icons/skill_mat/cadence_leaf.webp"},
"Cadence Blossom": { group: "ee", category: "domain", rank: 4, image: "ww_icons/skill_mat/cadence_blossom.webp"},
"Incomplete Combustor": { group: "ef", category: "domain", rank: 1, image: "ww_icons/skill_mat/tbc3.webp"},
"Aftertune Combustor": { group: "ef", category: "domain", rank: 2, image: "ww_icons/skill_mat/tbc3.webp"},
"Reverberation Combustor": { group: "ef", category: "domain", rank: 3, image: "ww_icons/skill_mat/tbc3.webp"},
"Remnant Combustor": { group: "ef", category: "domain", rank: 4, image: "ww_icons/skill_mat/tbc3.webp"},
"LF Carved Crystal": { group: "eg", category: "domain", rank: 1, image: "ww_icons/skill_mat/tbc3.webp"},
"MF Carved Crystal": { group: "eg", category: "domain", rank: 2, image: "ww_icons/skill_mat/tbc3.webp"},
"HF Carved Crystal": { group: "eg", category: "domain", rank: 3, image: "ww_icons/skill_mat/tbc3.webp"},
"FF Carved Crystal": { group: "eg", category: "domain", rank: 4, image: "ww_icons/skill_mat/tbc3.webp"},

/*Flowers*/
"TBC4": { group: "fa", category: "flower", rank: 0, image: "ww_icons/general/tbc4.webp"},
"Bamboo Iris": { group: "faa", category: "flower", rank: 0, image: "ww_icons/asc_mat/bamboo_iris.webp"},
"Belle Poppy": { group: "fab", category: "flower", rank: 0, image: "ww_icons/asc_mat/belle_poppy.webp"},
"Bloodleaf Viburnum": { group: "fac", category: "flower", rank: 0, image: "ww_icons/asc_mat/bloodleaf_viburnum.webp"},
"Coriolus": { group: "fad", category: "flower", rank: 0, image: "ww_icons/asc_mat/coriolus.webp"},
"Firecracker Jewelweed": { group: "fae", category: "flower", rank: 0, image: "ww_icons/asc_mat/firecracker_jewelweed.webp"},
"Golden Fleece": { group: "faf", category: "flower", rank: 0, image: "ww_icons/asc_mat/golden_fleece.webp"},
"Iris": { group: "fag", category: "flower", rank: 0, image: "ww_icons/asc_mat/iris.webp"},
"Lanternberry": { group: "fah", category: "flower", rank: 0, image: "ww_icons/asc_mat/lanternberry.webp"},
"Loong's Pearl": { group: "fai", category: "flower", rank: 0, image: "ww_icons/asc_mat/loongs_pearl.webp"},
"Nova": { group: "faj", category: "flower", rank: 0, image: "ww_icons/asc_mat/nova.webp"},
"Pavo Plum": { group: "fak", category: "flower", rank: 0, image: "ww_icons/asc_mat/pavo_plum.webp"},
"Pecok Flower": { group: "fal", category: "flower", rank: 0, image: "ww_icons/asc_mat/pecok_flower.webp"},
"Seaside Cendrelis": { group: "fam", category: "flower", rank: 0, image: "ww_icons/asc_mat/seaside_cendrelis.webp"},
"Sword Acorus": { group: "fan", category: "flower", rank: 0, image: "ww_icons/asc_mat/sword_acorus.webp"},
"Terraspawn Fungus": { group: "fao", category: "flower", rank: 0, image: "ww_icons/asc_mat/terraspawn_fungus.webp"},
"Violet Coral": { group: "fap", category: "flower", rank: 0, image: "ww_icons/asc_mat/violet_coral.webp"},
"Wintry Bell": { group: "faq", category: "flower", rank: 0, image: "ww_icons/asc_mat/wintry_bell.webp"},
"Afterlife": { group: "far", category: "flower", rank: 0, image: "ww_icons/asc_mat/afterlife.webp"},
"Luminous Calendula": { group: "fas", category: "flower", rank: 0, image: "ww_icons/asc_mat/luminous_calendula.webp"},
"Sliverglow Bloom": { group: "fat", category: "flower", rank: 0, image: "ww_icons/asc_mat/sliverglow_bloom.webp"},
"Stone Rose": { group: "fau", category: "flower", rank: 0, image: "ww_icons/asc_mat/stone_rose.webp"},
"Summer Flower": { group: "fav", category: "flower", rank: 0, image: "ww_icons/asc_mat/summer_flower.webp"},
};
