const skillRequirements = { 
augusta_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Waveworn Residue 210': 2, 'LF Tidal Residuum': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Waveworn Residue 210': 3, 'LF Tidal Residuum': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Waveworn Residue 226': 2, 'MF Tidal Residuum': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Waveworn Residue 226': 3, 'MF Tidal Residuum': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Waveworn Residue 235': 3, 'HF Tidal Residuum': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Waveworn Residue 235': 5, 'HF Tidal Residuum': 3, "When Irises Bloom": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Waveworn Residue 239': 2, 'FF Tidal Residuum': 2, "When Irises Bloom": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Waveworn Residue 239': 3, 'FF Tidal Residuum': 3, "When Irises Bloom": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Waveworn Residue 239': 6, 'FF Tidal Residuum': 4, "When Irises Bloom": 1 } },
],
brant_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'LF Tidal Residuum': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'LF Tidal Residuum': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'MF Tidal Residuum': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'MF Tidal Residuum': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'HF Tidal Residuum': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'HF Tidal Residuum': 3, "The Netherworld's Stare": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'FF Tidal Residuum': 2, "The Netherworld's Stare": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'FF Tidal Residuum': 3, "The Netherworld's Stare": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'FF Tidal Residuum': 4, "The Netherworld's Stare": 1 } },
],
buling_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Lento Helix': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Lento Helix': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Adagio Helix': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Adagio Helix': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Andante Helix': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Andante Helix': 5, 'HF Whisperin Core': 3, "Curse of the Abyss": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Presto Helix': 2, 'FF Whisperin Core': 2, "Curse of the Abyss": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Presto Helix': 3, 'FF Whisperin Core': 3, "Curse of the Abyss": 1 } },
{ from: 9, to: 10, items: { 'Shell Credits': 100000, 'Presto Helix': 6, 'FF Whisperin Core': 4, "Curse of the Abyss": 1 } }
],
calcharo_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Waveworn Residue 210': 2, 'Crude Ring': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Waveworn Residue 210': 3, 'Crude Ring': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Waveworn Residue 226': 2, 'Basic Ring': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Waveworn Residue 226': 3, 'Basic Ring': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Waveworn Residue 235': 3, 'Improved Ring': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Waveworn Residue 235': 5, 'Improved Ring': 3, "Monument Bell": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Waveworn Residue 239': 2, 'Tailored Ring': 2, "Monument Bell": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Waveworn Residue 239': 3, 'Tailored Ring': 3, "Monument Bell": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Waveworn Residue 239': 6, 'Tailored Ring': 4, "Monument Bell": 1 } },
],
camellya_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'HF Whisperin Core': 3, "Dreamless Feather": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'FF Whisperin Core': 2, "Dreamless Feather": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'FF Whisperin Core': 3, "Dreamless Feather": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'FF Whisperin Core': 4, "Dreamless Feather": 1 } },
],
cantarella_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Lento Helix': 2, 'LF Polygon Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Lento Helix': 3, 'LF Polygon Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Adagio Helix': 2, 'MF Polygon Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Adagio Helix': 3, 'MF Polygon Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Andante Helix': 3, 'HF Polygon Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Andante Helix': 5, 'HF Polygon Core': 3, "When Irises Bloom": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Presto Helix': 2, 'FF Polygon Core': 2, "When Irises Bloom": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Presto Helix': 3, 'FF Polygon Core': 3, "When Irises Bloom": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Presto Helix': 6, 'FF Polygon Core': 4, "When Irises Bloom": 1 } },
],
carlotta_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Impure Phlogiston': 2, 'LF Polygon Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Impure Phlogiston': 3, 'LF Polygon Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Extracted Phlogiston': 2, 'MF Polygon Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Extracted Phlogiston': 3, 'MF Polygon Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Refined Phlogiston': 3, 'HF Polygon Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Refined Phlogiston': 5, 'HF Polygon Core': 3, "The Netherworld's Stare": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Flawless Phlogiston': 2, 'FF Polygon Core': 2, "The Netherworld's Stare": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Flawless Phlogiston': 3, 'FF Polygon Core': 3, "The Netherworld's Stare": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Flawless Phlogiston': 6, 'FF Polygon Core': 4, "The Netherworld's Stare": 1 } },
],
cartethyia_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'LF Tidal Residuum': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'LF Tidal Residuum': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'MF Tidal Residuum': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'MF Tidal Residuum': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'HF Tidal Residuum': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'HF Tidal Residuum': 3, "When Irises Bloom": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'FF Tidal Residuum': 2, "When Irises Bloom": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'FF Tidal Residuum': 3, "When Irises Bloom": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'FF Tidal Residuum': 4, "When Irises Bloom": 1 } },
],
changli_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'Crude Ring': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'Crude Ring': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'Basic Ring': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'Basic Ring': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'Improved Ring': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'Improved Ring': 3, "Sentinel's Dagger": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'Tailored Ring': 2, "Sentinel's Dagger": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'Tailored Ring': 3, "Sentinel's Dagger": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'Tailored Ring': 4, "Sentinel's Dagger": 1 } },
],
chisa_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Waveworn Residue 210': 2, 'LF Polygon Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Waveworn Residue 210': 3, 'LF Polygon Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Waveworn Residue 226': 2, 'MF Polygon Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Waveworn Residue 226': 3, 'MF Polygon Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Waveworn Residue 235': 3, 'HF Polygon Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Waveworn Residue 235': 5, 'HF Polygon Core': 3, "When Irises Bloom": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Waveworn Residue 239': 2, 'FF Polygon Core': 2, "When Irises Bloom": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Waveworn Residue 239': 3, 'FF Polygon Core': 3, "When Irises Bloom": 1 } },
{ from: 9, to: 10, items: { 'Shell Credits': 100000, 'Waveworn Residue 239': 6, 'FF Polygon Core': 4, "When Irises Bloom": 1 } }
],
ciaccona_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Impure Phlogiston': 2, 'LF Tidal Residuum': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Impure Phlogiston': 3, 'LF Tidal Residuum': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Extracted Phlogiston': 2, 'MF Tidal Residuum': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Extracted Phlogiston': 3, 'MF Tidal Residuum': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Refined Phlogiston': 3, 'HF Tidal Residuum': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Refined Phlogiston': 5, 'HF Tidal Residuum': 3, "When Irises Bloom": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Flawless Phlogiston': 2, 'FF Tidal Residuum': 2, "When Irises Bloom": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Flawless Phlogiston': 3, 'FF Tidal Residuum': 3, "When Irises Bloom": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Flawless Phlogiston': 6, 'FF Tidal Residuum': 4, "When Irises Bloom": 1 } },
],
encore_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Lento Helix': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Lento Helix': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Adagio Helix': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Adagio Helix': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Andante Helix': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Andante Helix': 5, 'HF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Presto Helix': 2, 'FF Whisperin Core': 2, "Unending Destruction": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Presto Helix': 3, 'FF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Presto Helix': 6, 'FF Whisperin Core': 4, "Unending Destruction": 1 } },
],
galbrena_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Impure Phlogiston': 2, 'LF Tidal Residuum': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Impure Phlogiston': 3, 'LF Tidal Residuum': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Extracted Phlogiston': 2, 'MF Tidal Residuum': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Extracted Phlogiston': 3, 'MF Tidal Residuum': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Refined Phlogiston': 3, 'HF Tidal Residuum': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Refined Phlogiston': 5, 'HF Tidal Residuum': 3, "Curse of the Abyss": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Flawless Phlogiston': 2, 'FF Tidal Residuum': 2, "Curse of the Abyss": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Flawless Phlogiston': 3, 'FF Tidal Residuum': 3, "Curse of the Abyss": 1 } },
{ from: 9, to: 10, items: { 'Shell Credits': 100000, 'Flawless Phlogiston': 6, 'FF Tidal Residuum': 4, "Curse of the Abyss": 1 } },
],
iuno_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Cadence Seed': 2, 'LF Polygon Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Cadence Seed': 3, 'LF Polygon Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Cadence Bud': 2, 'MF Polygon Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Cadence Bud': 3, 'MF Polygon Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Cadence Leaf': 3, 'HF Polygon Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Cadence Leaf': 5, 'HF Polygon Core': 3, "The Netherworld's Stare": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Cadence Blossom': 2, 'FF Polygon Core': 2, "The Netherworld's Stare": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Cadence Blossom': 3, 'FF Polygon Core': 3, "The Netherworld's Stare": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Cadence Blossom': 6, 'FF Polygon Core': 4, "The Netherworld's Stare": 1 } },
],
jianxin_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Cadence Seed': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Cadence Seed': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Cadence Bud': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Cadence Bud': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Cadence Leaf': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Cadence Leaf': 5, 'HF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Cadence Blossom': 2, 'FF Whisperin Core': 2, "Unending Destruction": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Cadence Blossom': 3, 'FF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Cadence Blossom': 6, 'FF Whisperin Core': 4, "Unending Destruction": 1 } },
],
jinshi_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Waveworn Residue 210': 2, 'LF Howler Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Waveworn Residue 210': 3, 'LF Howler Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Waveworn Residue 226': 2, 'MF Howler Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Waveworn Residue 226': 3, 'MF Howler Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Waveworn Residue 235': 3, 'HF Howler Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Waveworn Residue 235': 5, 'HF Howler Core': 3, "Sentinel's Dagger": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Waveworn Residue 239': 2, 'FF Howler Core': 2, "Sentinel's Dagger": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Waveworn Residue 239': 3, 'FF Howler Core': 3, "Sentinel's Dagger": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Waveworn Residue 239': 6, 'FF Howler Core': 4, "Sentinel's Dagger": 1 } },
],
jiyan_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Waveworn Residue 210': 2, 'LF Howler Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Waveworn Residue 210': 3, 'LF Howler Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Waveworn Residue 226': 2, 'MF Howler Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Waveworn Residue 226': 3, 'MF Howler Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Waveworn Residue 235': 3, 'HF Howler Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Waveworn Residue 235': 5, 'HF Howler Core': 3, "Monument Bell": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Waveworn Residue 239': 2, 'FF Howler Core': 2, "Monument Bell": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Waveworn Residue 239': 3, 'FF Howler Core': 3, "Monument Bell": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Waveworn Residue 239': 6, 'FF Howler Core': 4, "Monument Bell": 1 } },
],
lingyang_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Cadence Seed': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Cadence Seed': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Cadence Bud': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Cadence Bud': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Cadence Leaf': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Cadence Leaf': 5, 'HF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Cadence Blossom': 2, 'FF Whisperin Core': 2, "Unending Destruction": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Cadence Blossom': 3, 'FF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Cadence Blossom': 6, 'FF Whisperin Core': 4, "Unending Destruction": 1 } },
],
lupa_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Waveworn Residue 210': 2, 'LF Howler Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Waveworn Residue 210': 3, 'LF Howler Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Waveworn Residue 226': 2, 'MF Howler Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Waveworn Residue 226': 3, 'MF Howler Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Waveworn Residue 235': 3, 'HF Howler Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Waveworn Residue 235': 5, 'HF Howler Core': 3, "The Netherworld's Stare": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Waveworn Residue 239': 2, 'FF Howler Core': 2, "The Netherworld's Stare": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Waveworn Residue 239': 3, 'FF Howler Core': 3, "The Netherworld's Stare": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Waveworn Residue 239': 6, 'FF Howler Core': 4, "The Netherworld's Stare": 1 } },
],
lynae_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Incomplete Combustor': 2, 'LF Exoswarm Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Incomplete Combustor': 3, 'LF Exoswarm Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Aftertune Combustor': 2, 'MF Exoswarm Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Aftertune Combustor': 3, 'MF Exoswarm Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Remnant Combustor': 3, 'HF Exoswarm Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Remnant Combustor': 5, 'HF Exoswarm Core': 3, "Dreamless Feather": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Reverb Combustor': 2, 'FF Exoswarm Core': 2, "Dreamless Feather": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Reverb Combustor': 3, 'FF Exoswarm Core': 3, "Dreamless Feather": 1 } },
{ from: 9, to: 10, items: { 'Shell Credits': 100000, 'Reverb Combustor': 6, 'FF Exoswarm Core': 4, "Dreamless Feather": 1 } }
],
mornye_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'LF Carved Crystal': 2, 'LF Mech Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'LF Carved Crystal': 3, 'LF Mech Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'MF Carved Crystal': 2, 'MF Mech Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'MF Carved Crystal': 3, 'MF Mech Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'HF Carved Crystal': 3, 'HF Mech Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'HF Carved Crystal': 5, 'HF Mech Core': 3, "The Netherworld's Stare": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'FF Carved Crystal': 2, 'FF Mech Core': 2, "The Netherworld's Stare": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'FF Carved Crystal': 3, 'FF Mech Core': 3, "The Netherworld's Stare": 1 } },
{ from: 9, to: 10, items: { 'Shell Credits': 100000, 'FF Carved Crystal': 6, 'FF Mech Core': 4, "The Netherworld's Stare": 1 } }
],
phoebe_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Lento Helix': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Lento Helix': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Adagio Helix': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Adagio Helix': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Andante Helix': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Andante Helix': 5, 'HF Whisperin Core': 3, "Sentinel's Dagger": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Presto Helix': 2, 'FF Whisperin Core': 2, "Sentinel's Dagger": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Presto Helix': 3, 'FF Whisperin Core': 3, "Sentinel's Dagger": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Presto Helix': 6, 'FF Whisperin Core': 4, "Sentinel's Dagger": 1 } },
],
phrolova_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Lento Helix': 2, 'LF Polygon Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Lento Helix': 3, 'LF Polygon Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Adagio Helix': 2, 'MF Polygon Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Adagio Helix': 3, 'MF Polygon Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Andante Helix': 3, 'HF Polygon Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Andante Helix': 5, 'HF Polygon Core': 3, "The Netherworld's Stare": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Presto Helix': 2, 'FF Polygon Core': 2, "The Netherworld's Stare": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Presto Helix': 3, 'FF Polygon Core': 3, "The Netherworld's Stare": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Presto Helix': 6, 'FF Polygon Core': 4, "The Netherworld's Stare": 1 } },
],
qiuyuan_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'HF Whisperin Core': 3, "Curse of the Abyss": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'FF Whisperin Core': 2, "Curse of the Abyss": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'FF Whisperin Core': 3, "Curse of the Abyss": 1 } },
{ from: 9, to: 10, items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'FF Whisperin Core': 4, "Curse of the Abyss": 1 } }
],
roccia_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Cadence Seed': 2, 'LF Tidal Residuum': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Cadence Seed': 3, 'LF Tidal Residuum': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Cadence Bud': 2, 'MF Tidal Residuum': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Cadence Bud': 3, 'MF Tidal Residuum': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Cadence Leaf': 3, 'HF Tidal Residuum': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Cadence Leaf': 5, 'HF Tidal Residuum': 3, "The Netherworld's Stare": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Cadence Blossom': 2, 'FF Tidal Residuum': 2, "The Netherworld's Stare": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Cadence Blossom': 3, 'FF Tidal Residuum': 3, "The Netherworld's Stare": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Cadence Blossom': 6, 'FF Tidal Residuum': 4, "The Netherworld's Stare": 1 } },
],
rover_aero_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'HF Whisperin Core': 3, "When Irises Bloom": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'FF Whisperin Core': 2, "When Irises Bloom": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'FF Whisperin Core': 3, "When Irises Bloom": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'FF Whisperin Core': 4, "When Irises Bloom": 1 } },
],
rover_havoc_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'HF Whisperin Core': 3, "Dreamless Feather": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'FF Whisperin Core': 2, "Dreamless Feather": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'FF Whisperin Core': 3, "Dreamless Feather": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'FF Whisperin Core': 4, "Dreamless Feather": 1 } },
],
rover_spectro_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'HF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'FF Whisperin Core': 2, "Unending Destruction": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'FF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'FF Whisperin Core': 4, "Unending Destruction": 1 } },
],
shorekeeper_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Lento Helix': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Lento Helix': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Adagio Helix': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Adagio Helix': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Andante Helix': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Andante Helix': 5, 'HF Whisperin Core': 3, "Sentinel's Dagger": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Presto Helix': 2, 'FF Whisperin Core': 2, "Sentinel's Dagger": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Presto Helix': 3, 'FF Whisperin Core': 3, "Sentinel's Dagger": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Presto Helix': 6, 'FF Whisperin Core': 4, "Sentinel's Dagger": 1 } },
],
verina_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Lento Helix': 2, 'LF Howler Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Lento Helix': 3, 'LF Howler Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Adagio Helix': 2, 'MF Howler Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Adagio Helix': 3, 'MF Howler Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Andante Helix': 3, 'HF Howler Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Andante Helix': 5, 'HF Howler Core': 3, "Monument Bell": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Presto Helix': 2, 'FF Howler Core': 2, "Monument Bell": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Presto Helix': 3, 'FF Howler Core': 3, "Monument Bell": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Presto Helix': 6, 'FF Howler Core': 4, "Monument Bell": 1 } },
],
xiangli_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Cadence Seed': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Cadence Seed': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Cadence Bud': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Cadence Bud': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Cadence Leaf': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Cadence Leaf': 5, 'HF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Cadence Blossom': 2, 'FF Whisperin Core': 2, "Unending Destruction": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Cadence Blossom': 3, 'FF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Cadence Blossom': 6, 'FF Whisperin Core': 4, "Unending Destruction": 1 } },
],
yinlin_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Lento Helix': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Lento Helix': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Adagio Helix': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Adagio Helix': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Andante Helix': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Andante Helix': 5, 'HF Whisperin Core': 3, "Dreamless Feather": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Presto Helix': 2, 'FF Whisperin Core': 2, "Dreamless Feather": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Presto Helix': 3, 'FF Whisperin Core': 3, "Dreamless Feather": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Presto Helix': 6, 'FF Whisperin Core': 4, "Dreamless Feather": 1 } },
],
zani_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Cadence Seed': 2, 'LF Polygon Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Cadence Seed': 3, 'LF Polygon Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Cadence Bud': 2, 'MF Polygon Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Cadence Bud': 3, 'MF Polygon Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Cadence Leaf': 3, 'HF Polygon Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Cadence Leaf': 5, 'HF Polygon Core': 3, "The Netherworld's Stare": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Cadence Blossom': 2, 'FF Polygon Core': 2, "The Netherworld's Stare": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Cadence Blossom': 3, 'FF Polygon Core': 3, "The Netherworld's Stare": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Cadence Blossom': 6, 'FF Polygon Core': 4, "The Netherworld's Stare": 1 } },
],
zhezhi_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Lento Helix': 2, 'LF Howler Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Lento Helix': 3, 'LF Howler Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Adagio Helix': 2, 'MF Howler Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Adagio Helix': 3, 'MF Howler Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Andante Helix': 3, 'HF Howler Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Andante Helix': 5, 'HF Howler Core': 3, "Monument Bell": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Presto Helix': 2, 'FF Howler Core': 2, "Monument Bell": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Presto Helix': 3, 'FF Howler Core': 3, "Monument Bell": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Presto Helix': 6, 'FF Howler Core': 4, "Monument Bell": 1 } },
],
aalto_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Impure Phlogiston': 2, 'LF Howler Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Impure Phlogiston': 3, 'LF Howler Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Extracted Phlogiston': 2, 'MF Howler Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Extracted Phlogiston': 3, 'MF Howler Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Refined Phlogiston': 3, 'HF Howler Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Refined Phlogiston': 5, 'HF Howler Core': 3, "Monument Bell": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Flawless Phlogiston': 2, 'FF Howler Core': 2, "Monument Bell": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Flawless Phlogiston': 3, 'FF Howler Core': 3, "Monument Bell": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Flawless Phlogiston': 6, 'FF Howler Core': 4, "Monument Bell": 1 } },
],
baizhi_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Lento Helix': 2, 'LF Howler Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Lento Helix': 3, 'LF Howler Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Adagio Helix': 2, 'MF Howler Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Adagio Helix': 3, 'MF Howler Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Andante Helix': 3, 'HF Howler Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Andante Helix': 5, 'HF Howler Core': 3, "Monument Bell": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Presto Helix': 2, 'FF Howler Core': 2, "Monument Bell": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Presto Helix': 3, 'FF Howler Core': 3, "Monument Bell": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Presto Helix': 6, 'FF Howler Core': 4, "Monument Bell": 1 } },
],
chixia_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Impure Phlogiston': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Impure Phlogiston': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Extracted Phlogiston': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Extracted Phlogiston': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Refined Phlogiston': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Refined Phlogiston': 5, 'HF Whisperin Core': 3, "Monument Bell": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Flawless Phlogiston': 2, 'FF Whisperin Core': 2, "Monument Bell": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Flawless Phlogiston': 3, 'FF Whisperin Core': 3, "Monument Bell": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Flawless Phlogiston': 6, 'FF Whisperin Core': 4, "Monument Bell": 1 } },
],
danjin_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'Crude Ring': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'Crude Ring': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'Basic Ring': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'Basic Ring': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'Improved Ring': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'Improved Ring': 3, "Dreamless Feather": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'Tailored Ring': 2, "Dreamless Feather": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'Tailored Ring': 3, "Dreamless Feather": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'Tailored Ring': 4, "Dreamless Feather": 1 } },
],
lumi_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Waveworn Residue 210': 2, 'LF Howler Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Waveworn Residue 210': 3, 'LF Howler Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Waveworn Residue 226': 2, 'MF Howler Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Waveworn Residue 226': 3, 'MF Howler Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Waveworn Residue 235': 3, 'HF Howler Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Waveworn Residue 235': 5, 'HF Howler Core': 3, "Sentinel's Dagger": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Waveworn Residue 239': 2, 'FF Howler Core': 2, "Sentinel's Dagger": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Waveworn Residue 239': 3, 'FF Howler Core': 3, "Sentinel's Dagger": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Waveworn Residue 239': 6, 'FF Howler Core': 4, "Sentinel's Dagger": 1 } },
],
mortefi_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Impure Phlogiston': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Impure Phlogiston': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Extracted Phlogiston': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Extracted Phlogiston': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Refined Phlogiston': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Refined Phlogiston': 5, 'HF Whisperin Core': 3, "Monument Bell": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Flawless Phlogiston': 2, 'FF Whisperin Core': 2, "Monument Bell": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Flawless Phlogiston': 3, 'FF Whisperin Core': 3, "Monument Bell": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Flawless Phlogiston': 6, 'FF Whisperin Core': 4, "Monument Bell": 1 } },
],
sanhua_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'LF Whisperin Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'LF Whisperin Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'MF Whisperin Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'MF Whisperin Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'HF Whisperin Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'HF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'FF Whisperin Core': 2, "Unending Destruction": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'FF Whisperin Core': 3, "Unending Destruction": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'FF Whisperin Core': 4, "Unending Destruction": 1 } },
],
taoqi_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Waveworn Residue 210': 2, 'LF Howler Core': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Waveworn Residue 210': 3, 'LF Howler Core': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Waveworn Residue 226': 2, 'MF Howler Core': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Waveworn Residue 226': 3, 'MF Howler Core': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Waveworn Residue 235': 3, 'HF Howler Core': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Waveworn Residue 235': 5, 'HF Howler Core': 3, "Dreamless Feather": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Waveworn Residue 239': 2, 'FF Howler Core': 2, "Dreamless Feather": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Waveworn Residue 239': 3, 'FF Howler Core': 3, "Dreamless Feather": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Waveworn Residue 239': 6, 'FF Howler Core': 4, "Dreamless Feather": 1 } },
],
yangyang_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Inert Metallic Drip': 2, 'Crude Ring': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Inert Metallic Drip': 3, 'Crude Ring': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Reactive Metallic Drip': 2, 'Basic Ring': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Reactive Metallic Drip': 3, 'Basic Ring': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Polarized Metallic Drip': 3, 'Improved Ring': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Polarized Metallic Drip': 5, 'Improved Ring': 3, "Unending Destruction": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Heterized Metallic Drip': 2, 'Tailored Ring': 2, "Unending Destruction": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Heterized Metallic Drip': 3, 'Tailored Ring': 3, "Unending Destruction": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Heterized Metallic Drip': 6, 'Tailored Ring': 4, "Unending Destruction": 1 } },
],
youhu_req: [
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Cadence Seed': 2, 'Crude Ring': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Cadence Seed': 3, 'Crude Ring': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Cadence Bud': 2, 'Basic Ring': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Cadence Bud': 3, 'Basic Ring': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Cadence Leaf': 3, 'Improved Ring': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Cadence Leaf': 5, 'Improved Ring': 3, "Monument Bell": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Cadence Blossom': 2, 'Tailored Ring': 2, "Monument Bell": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Cadence Blossom': 3, 'Tailored Ring': 3, "Monument Bell": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Cadence Blossom': 6, 'Tailored Ring': 4, "Monument Bell": 1 } },
],
yuanwu_req: [ 
{ from: 1, to: 2, items: { 'Shell Credits': 1500, 'Cadence Seed': 2, 'Crude Ring': 2 } },
{ from: 2, to: 3, items: { 'Shell Credits': 2000, 'Cadence Seed': 3, 'Crude Ring': 3 } },
{ from: 3, to: 4, items: { 'Shell Credits': 4500, 'Cadence Bud': 2, 'Basic Ring': 2 } },
{ from: 4, to: 5, items: { 'Shell Credits': 6000, 'Cadence Bud': 3, 'Basic Ring': 3 } },
{ from: 5, to: 6, items: { 'Shell Credits': 16000, 'Cadence Leaf': 3, 'Improved Ring': 2 } },
{ from: 6, to: 7, items: { 'Shell Credits': 30000, 'Cadence Leaf': 5, 'Improved Ring': 3, "Unending Destruction": 1 } },
{ from: 7, to: 8, items: { 'Shell Credits': 50000, 'Cadence Blossom': 2, 'Tailored Ring': 2, "Unending Destruction": 1 } },
{ from: 8, to: 9, items: { 'Shell Credits': 70000, 'Cadence Blossom': 3, 'Tailored Ring': 3, "Unending Destruction": 1 } },
{ from: 9, to: 10,items: { 'Shell Credits': 100000, 'Cadence Blossom': 6, 'Tailored Ring': 4, "Unending Destruction": 1 } },
],
};
